name: simenkou roads trace task
on:
  schedule:
    - cron: '*/5 22-23,0-14 * * *'           # 非高峰期每半小时执行一次(用10min做测试)  UTC+8 6-22
    
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run python task
        env:
          API_KEY: ${{ secrets.TCB_API_KEY }}
        run: |
          python focus_request.py
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: ./result
      - name: Push result
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:  |        
          git config --global user.email "channing_tongcn@outlook.com"
          git config --global user.name "channing tong"  
          git add -A
          git commit -m "update inner ring roads trunk infomation"
          git push origin main
