name: innner ring roads trace task
on:
  schedule:
    - cron: '*/10 22-23,1-9 * * *'           # 非高峰期每半小时执行一次(用10min做测试)  UTC+8 6-7
    - cron: '*/10 23,0-1,9-11 * * *'       # 高峰期每十分钟执行一次   UTC+8 7-9,17-19
    
  # workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run python task
        env:
          API_KEY: ${{ secrets.MYM_API_KEY }}
        run: |
          python scrtransport_request.py
