name: innner ring roads trace task
on:
  schedule:
    - cron: '40 22 * * *'         # 每天06:30
    - cron: '*/20 23,0-11 * * *'  # 每20分钟检测一次
    
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run python task
        env:
          API_KEY: ${{ secrets.TCB_API_KEY }}
        run: |
          python transport_request.py
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: ./result
      - name: Push result
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:  |        
          git config --global user.email "channing_tongcn@outlook.com"
          git config --global user.name "channing tong"  
          git config --global pull.rebase true
          git add -A
          git commit -m "update inner ring roads trunk infomation"
          git pull origin main
          git push -f origin main
